name: fastfoodapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  http: 0.13.6
  logger: ^2.0.1
  url_launcher: ^6.1.12
  get: ^4.6.5
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  readmore: ^2.2.0

  # thư viện cho phần ở details product
  clippy_flutter: ^2.0.0-nullsafety.1
  # Thư viện icon đánh giá
  
  flutterflow_ui: ^0.2.0+1

  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:

  - images/
  - assets/images/
  - assets/images/reviews/
  - assets/images/products/
  - assets/images/payment_methods/
  - assets/foods/Category/
  - assets/foods/Bestsell/
  - assets/banner/
  

