name: fastfoodapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1 
  intl: ^0.19.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/foods/Category/
  - assets/foods/Bestsell/
  - assets/banner/
  